server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: gmontinny
    password: password

keycloak:
  realm: master
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8180}/auth
  resource: spring-app
  bearer-only: true